// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using TheFund.AtidsXe.Data.Entities;

namespace TheFund.AtidsXe.Data.Configuration
{
    public class OwnerBuyerRelationshipConfiguration : IEntityTypeConfiguration<OwnerBuyerRelationship>
    {
        public void Configure(EntityTypeBuilder<OwnerBuyerRelationship> entity)
        {
            entity.ToTable("OWNER_BUYER_RELATIONSHIP");

            entity.Property(e => e.OwnerBuyerRelationshipId)
                .HasColumnName("OWNER_BUYER_RELATIONSHIP_ID")
                .ValueGeneratedNever();

            entity.Property(e => e.Description)
                .HasColumnName("DESCRIPTION")
                .HasMaxLength(50)
                .IsUnicode(false);
        }
    }
}
