// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using TheFund.AtidsXe.Data.Entities;

namespace TheFund.AtidsXe.Data.Configuration
{
    public class PlatReferenceConfiguration : IEntityTypeConfiguration<PlatReference>
    {
        public void Configure(EntityTypeBuilder<PlatReference> entity)
        {
            entity.ToTable("PLAT_REFERENCE");

            entity.Property(e => e.PlatReferenceId).HasColumnName("PLAT_REFERENCE_ID");

            entity.Property(e => e.Book)
                .IsRequired()
                .HasColumnName("BOOK")
                .HasMaxLength(5)
                .IsUnicode(false);

            entity.Property(e => e.BookSuffix)
                .HasColumnName("BOOK_SUFFIX")
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.Page)
                .IsRequired()
                .HasColumnName("PAGE")
                .HasMaxLength(7)
                .IsUnicode(false);

            entity.Property(e => e.PageSuffix)
                .HasColumnName("PAGE_SUFFIX")
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.Source)
                .IsRequired()
                .HasColumnName("SOURCE")
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength();
        }
    }
}
