// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using TheFund.AtidsXe.Data.Entities;

namespace TheFund.AtidsXe.Data.Configuration
{
    public class PolicyRestrictionTypeConfiguration : IEntityTypeConfiguration<PolicyRestrictionType>
    {
        public void Configure(EntityTypeBuilder<PolicyRestrictionType> entity)
        {
            entity.ToTable("POLICY_RESTRICTION_TYPE");

            entity.Property(e => e.PolicyRestrictionTypeId).HasColumnName("POLICY_RESTRICTION_TYPE_ID");

            entity.Property(e => e.Description)
                .IsRequired()
                .HasColumnName("DESCRIPTION")
                .HasMaxLength(25)
                .IsUnicode(false);
        }
    }
}
