// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using TheFund.AtidsXe.Data.Entities;

namespace TheFund.AtidsXe.Data.Configuration
{
    public class PolicySearchConfiguration : IEntityTypeConfiguration<PolicySearch>
    {
        public void Configure(EntityTypeBuilder<PolicySearch> entity)
        {
            entity.HasKey(e => new { e.PolicyId, e.SearchId });

            entity.ToTable("POLICY_SEARCH");

            entity.HasIndex(e => e.SearchId)
                .HasName("I_FK_POLICY_SEARCH_SEARCH_ID");

            entity.Property(e => e.PolicyId).HasColumnName("POLICY_ID");

            entity.Property(e => e.SearchId).HasColumnName("SEARCH_ID");

            entity.HasOne(d => d.Policy)
                .WithMany(p => p.PolicySearches)
                .HasForeignKey(d => d.PolicyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_POLICY_POLICY_SEARCH");

            entity.HasOne(d => d.Search)
                .WithMany(p => p.PolicySearches)
                .HasForeignKey(d => d.SearchId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SEARCH_POLICY_SEARCH");
        }
    }
}
