// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using TheFund.AtidsXe.Data.Entities;

namespace TheFund.AtidsXe.Data.Configuration
{
    public class RangeDirectionTypeConfiguration : IEntityTypeConfiguration<RangeDirectionType>
    {
        public void Configure(EntityTypeBuilder<RangeDirectionType> entity)
        {
            entity.ToTable("RANGE_DIRECTION_TYPE");

            entity.Property(e => e.RangeDirectionTypeId)
                .HasColumnName("RANGE_DIRECTION_TYPE_ID")
                .ValueGeneratedNever();

            entity.Property(e => e.Description)
                .IsRequired()
                .HasColumnName("DESCRIPTION")
                .HasMaxLength(16)
                .IsUnicode(false);
        }
    }
}
