// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using TheFund.AtidsXe.Data.Entities;

namespace TheFund.AtidsXe.Data.Configuration
{
    public class SectionLegalConfiguration : IEntityTypeConfiguration<SectionLegal>
    {
        public void Configure(EntityTypeBuilder<SectionLegal> entity)
        {
            entity.HasKey(e => new { e.SectionBreakdownCodeId, e.UnplattedReferenceId });

            entity.ToTable("SECTION_LEGAL");

            entity.HasIndex(e => e.UnplattedReferenceId)
                .HasName("I_FK_SECTION_LEGAL_UNPLATTED_REFERENCE_ID");

            entity.Property(e => e.SectionBreakdownCodeId).HasColumnName("SECTION_BREAKDOWN_CODE_ID");

            entity.Property(e => e.UnplattedReferenceId).HasColumnName("UNPLATTED_REFERENCE_ID");

            entity.HasOne(d => d.SectionBreakdownCode)
                .WithMany(p => p.SectionLegal)
                .HasForeignKey(d => d.SectionBreakdownCodeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SECT_BRKDWN_CD_SECT_LEGAL");

            entity.HasOne(d => d.UnplattedReference)
                .WithMany(p => p.SectionLegal)
                .HasForeignKey(d => d.UnplattedReferenceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UNPLATTED_REF_SECT_LEGAL");
        }
    }
}
