// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using TheFund.AtidsXe.Data.Entities;

namespace TheFund.AtidsXe.Data.Configuration
{
    public class SubdivisionLevelsConfiguration : IEntityTypeConfiguration<SubdivisionLevels>
    {
        public void Configure(EntityTypeBuilder<SubdivisionLevels> entity)
        {
            entity.HasKey(e => e.SubdivisionLevelId);

            entity.ToTable("SUBDIVISION_LEVELS");

            entity.HasIndex(e => new { e.Level1, e.Level2, e.Level3 })
                .HasName("SUBDIVISION_LEVELS_UC1")
                .IsUnique();

            entity.Property(e => e.SubdivisionLevelId).HasColumnName("SUBDIVISION_LEVEL_ID");

            entity.Property(e => e.Level1)
                .IsRequired()
                .HasColumnName("LEVEL1")
                .HasMaxLength(6)
                .IsUnicode(false);

            entity.Property(e => e.Level2)
                .IsRequired()
                .HasColumnName("LEVEL2")
                .HasMaxLength(6)
                .IsUnicode(false);

            entity.Property(e => e.Level3)
                .IsRequired()
                .HasColumnName("LEVEL3")
                .HasMaxLength(6)
                .IsUnicode(false);
        }
    }
}
