// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TheFund.AtidsXe.Data.Entities;

namespace TheFund.AtidsXe.Data.Configuration
{
    public class TitleEventConfiguration : IEntityTypeConfiguration<TitleEvent>
    {
        public void Configure(EntityTypeBuilder<TitleEvent> entity)
        {
            entity.ToTable("TITLE_EVENT");

            entity.HasIndex(e => e.CurrentExamStatusTypeId)
                .HasName("I_CURRENT_EXAM_STATUS_TYPE");

            entity.HasIndex(e => e.OriginalExamStatusTypeId)
                .HasName("I_ORIGINAL_EXAM_STATUS");

            entity.HasIndex(e => e.TitleEventStatusAssignorId)
                .HasName("I_TITLE_EVT_STAT_ASSIGNOR");

            entity.HasIndex(e => e.TitleEventTypeId)
                .HasName("I_EVENT_TYPE");

            entity.Property(e => e.TitleEventId).HasColumnName("TITLE_EVENT_ID");

            entity.Property(e => e.AdditionalInformation)
                .HasColumnName("ADDITIONAL_INFORMATION")
                .HasMaxLength(15)
                .IsUnicode(false);

            entity.Property(e => e.Amount)
                .HasColumnName("AMOUNT")
                .HasColumnType("numeric(13, 2)");

            entity.Property(e => e.CreateDate)
                .HasColumnName("CREATE_DATE")
                .HasColumnType("datetime")
                .HasDefaultValueSql("(getdate())");

            entity.Property(e => e.CurrentExamStatusTypeId).HasColumnName("CURRENT_EXAM_STATUS_TYPE_ID");

            entity.Property(e => e.OriginalExamStatusTypeId).HasColumnName("ORIGINAL_EXAM_STATUS_TYPE_ID");

            entity.Property(e => e.Tag)
                .HasColumnName("TAG")
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.TitleEventDate)
                .HasColumnName("TITLE_EVENT_DATE")
                .HasColumnType("datetime");

            entity.Property(e => e.TitleEventStatusAssignorId).HasColumnName("TITLE_EVENT_STATUS_ASSIGNOR_ID");

            entity.Property(e => e.TitleEventTypeId).HasColumnName("TITLE_EVENT_TYPE_ID");
        }
    }
}
