// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using TheFund.AtidsXe.Data.Entities;

namespace TheFund.AtidsXe.Data.Configuration
{
    public class TitleEventOrderConfiguration : IEntityTypeConfiguration<TitleEventOrder>
    {
        public void Configure(EntityTypeBuilder<TitleEventOrder> entity)
        {
            entity.ToTable("TITLE_EVENT_ORDER");

            entity.HasIndex(e => e.TrackingIdentifier);

            entity.Property(e => e.TitleEventOrderId).HasColumnName("TITLE_EVENT_ORDER_ID");

            entity.Property(e => e.OrderDate)
                .HasColumnName("ORDER_DATE")
                .HasColumnType("datetime");

            entity.Property(e => e.TrackingIdentifier)
                .IsRequired()
                .HasColumnName("TRACKING_IDENTIFIER")
                .HasMaxLength(60)
                .IsUnicode(false);
        }
    }
}
