// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using TheFund.AtidsXe.Data.Entities;

namespace TheFund.AtidsXe.Data.Configuration
{
    public class TitleEventPartyConfiguration : IEntityTypeConfiguration<TitleEventParty>
    {
        public void Configure(EntityTypeBuilder<TitleEventParty> entity)
        {
            entity.HasKey(e => new { e.TitleEventId, e.PartyId });

            entity.ToTable("TITLE_EVENT_PARTY");

            entity.HasIndex(e => e.PartyId)
                .HasName("I_FK_TITLE_EVENT_PARTY_PARTY_ID");

            entity.Property(e => e.TitleEventId).HasColumnName("TITLE_EVENT_ID");

            entity.Property(e => e.PartyId).HasColumnName("PARTY_ID");

            entity.HasOne(d => d.Party)
                .WithMany(p => p.TitleEventParty)
                .HasForeignKey(d => d.PartyId)
                .HasConstraintName("FK_PARTY_TITLE_EVENT_PARTY");

            entity.HasOne(d => d.TitleEvent)
                .WithMany(p => p.TitleEventParty)
                .HasForeignKey(d => d.TitleEventId)
                .HasConstraintName("FK_TITLE_EVENT_PARTY");
        }
    }
}
