// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using TheFund.AtidsXe.Data.Entities;

namespace TheFund.AtidsXe.Data.Configuration
{
    public class TitleEventDocumentConfiguration : IEntityTypeConfiguration<TitleEventDocument>
    {
        public void Configure(EntityTypeBuilder<TitleEventDocument> entity)
        {
            entity.HasKey(e => new { e.TitleEventId, e.OfficialRecordDocumentId });

            entity.ToTable("TITLE_EVENT_DOCUMENT");

            entity.HasIndex(e => e.OfficialRecordDocumentId)
                .HasName("I_TITLE_EVENT_DOCUMENT_OFF_REC_DOC_ID");

            entity.HasIndex(e => e.TitleEventId)
                .HasName("UC_TITLE_EVENT_DOCUMENT")
                .IsUnique();

            entity.Property(e => e.TitleEventId).HasColumnName("TITLE_EVENT_ID");

            entity.Property(e => e.OfficialRecordDocumentId).HasColumnName("OFFICIAL_RECORD_DOCUMENT_ID");

            entity.HasOne(d => d.OfficialRecordDocument)
                .WithMany(p => p.TitleEventDocument)
                .HasForeignKey(d => d.OfficialRecordDocumentId)
                .HasConstraintName("FK_ORD_TITLE_EVENT");

            entity.HasOne(d => d.TitleEvent)
                .WithOne(p => p.TitleEventDocument)
                .HasForeignKey<TitleEventDocument>(d => d.TitleEventId)
                .HasConstraintName("FK_TITLE_EVENT_DOCUMENTS");
        }
    }
}
