// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using TheFund.AtidsXe.Data.Entities;

namespace TheFund.AtidsXe.Data.Configuration
{
    public class YearNumberReferenceConfiguration : IEntityTypeConfiguration<YearNumberReference>
    {
        public void Configure(EntityTypeBuilder<YearNumberReference> entity)
        {
            entity.HasKey(e => e.OfficialRecordDocumentId);

            entity.ToTable("YEAR_NUMBER_REFERENCE");

            entity.Property(e => e.OfficialRecordDocumentId)
                .HasColumnName("OFFICIAL_RECORD_DOCUMENT_ID")
                .ValueGeneratedNever();

            entity.Property(e => e.RecordingNumber).HasColumnName("RECORDING_NUMBER");

            entity.Property(e => e.RecordingYear).HasColumnName("RECORDING_YEAR");

            entity.Property(e => e.SeriesCode)
                .HasColumnName("SERIES_CODE")
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.Source)
                .IsRequired()
                .HasColumnName("SOURCE")
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.Suffix)
                .HasColumnName("SUFFIX")
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength();

            entity.HasOne(d => d.OfficialRecordDocument)
                .WithOne(p => p.YearNumberReference)
                .HasForeignKey<YearNumberReference>(d => d.OfficialRecordDocumentId)
                .HasConstraintName("FK_ORD_YEAR_NUMBER_REF");
        }
    }
}
